name: Deployment

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]  # Node.js version specify karein

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Repo ka code checkout karein
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      # Step 2: Node.js set up karein
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Dependencies install karein
      - name: Install Packages
        run: npm install

      # Step 4: Project build karein (if needed)
      - name: Build page
        run: npm run build  # Agar aapka project build step use karta hai

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public  # Yahan `public` folder specify karein
          github_token: ${{ secrets.GITHUB_TOKEN }}
